# Generated by Django 4.2.4 on 2023-09-17 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=64)),
                ('ano', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Carros',
                'db_table': 'carros',
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Cores',
                'db_table': 'cores',
            },
        ),
        migrations.CreateModel(
            name='Personalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('descricao', models.TextField()),
                ('carros', models.ManyToManyField(related_name='carros', to='portal.carro')),
            ],
            options={
                'verbose_name_plural': 'Personalizações',
                'db_table': 'personalizacoes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('sobrenome', models.CharField(max_length=128)),
                ('admin', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=128)),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('celular', models.CharField(max_length=19, null=True)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(verbose_name='Data de criação')),
                ('personalizacoes', models.ManyToManyField(related_name='personalizacoes', to='portal.personalizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
                'db_table': 'solicitacoes',
            },
        ),
        migrations.AddField(
            model_name='carro',
            name='cores',
            field=models.ManyToManyField(to='portal.cor'),
        ),
    ]
