# Generated by Django 4.2.4 on 2023-10-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enviada'), (2, 'Em negociação'), (3, 'Em produção'), (4, 'Atendida')], default=0),
        ),
    ]
