# Generated by Django 4.2.4 on 2023-09-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
