# Generated by Django 4.2.4 on 2023-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.IntegerField(choices=[(0, 'Enviada'), (1, 'Em negociação'), (2, 'Em produção'), (3, 'Atendida')], default=0),
        ),
    ]
