# Generated by Django 4.2.4 on 2023-09-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_personalizacao_carros_carro_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='descricao',
            field=models.CharField(default='Descubra a potência inigualável e a tecnologia surpreendente da', max_length=256),
            preserve_default=False,
        ),
    ]
